In [ ]:
from google.colab import drive
drive.mount('/content/drive')
# !pip install hdf5storage
# !pip install ipdb

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# !cp -r drive/MyDrive/slog-net/SLOGmodules .
!cp -r drive/MyDrive/slog-net/SLoGexample .

In [ ]:
# %cd /content/drive/MyDrive/slog-net/SLoGexample
# %cd /content/drive/MyDrive/slog-net

In [ ]:
username = 'Yechang618'
repository = 'SLoG-Net-Example'
git_token = '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'
# !git status
# !ls -a
# !git init SLoGexample
# !git add .
# !git commit -m "The first update"
# !git config --global user.email "yechang618@gmail.com"
# !git config --global user.name "Chang Ye"
# !git remote prune origin
# !git remote add origin https://{git_token}@github.com/{username}/{repository}.git
# !git remote remove yechang618
# !git push -u origin master
# !git remote -v

In [ ]:
# !cp -r drive/MyDrive/slog-net/SLoGexample .
import numpy as np
from numpy import linalg as LA
import torch; torch.set_default_dtype(torch.float64)
import torch.nn as nn
import torch.optim as optim
import copy
from copy import deepcopy
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy import linalg
from timeit import default_timer as timer
import networkx as nx
import os
import pickle
import datetime
#### Import SLOG packakes
from SLoGexample import SLOGexperiment as SLOGexperiment
import torch
import os

In [ ]:
useGPU = True
if useGPU and torch.cuda.is_available():
    device = 'cuda:0'
    torch.cuda.empty_cache()
else:
    device = 'cpu'
# Notify:
device = torch.device(device)
print("Device selected: %s" % device)

Device selected: cpu


Parameters

In [ ]:
### Model parameters
K = 5 # number of layers

filterTrainType = 'h'
### Simulation parameters
simuParas = {}
nTrain = 20000
P = 100
batchsize = P
# nValid = batchsize_slog
# nTest = batchsize_slog
nValid = P
nTest = P
nEpochs = 20
early_stop_criteria = 1e-5
### Data parameters
L = 5
alpha = 1.0

### Graph parameters

nNodes = 20 # Number of nodes
S = int(0.15*nNodes) # Number of sources per signal
C = nNodes # constrain constant
q = 2 # Number of constrain vectors for SLOG-Net-v3
simuParas['nNodes'] = nNodes
simuParas['S'] = S

graphType = 'ER' # Type of graph
graphOptions = {} # Dictionary of options to pass to the graphTools.createGraph function
graphOptions['probIntra'] = 0.3 # Probability of drawing edges


## Filter type: g or h
filterType = 'h'
## Signal mode: gaussion or 1
signalMode = 'Gaussion'
## Train mode: Wt or default (Vdiag(\tilde{h})V^T)
trainMode = 'default'
## Filter mode: Wt or default (Vdiag(\tilde{h})V^T)
filterMode = 'default'

## Selection mode: random or nodes with top-N_C degree
selectMode = 'random'

## Noise level
noiseLevel = 0.0
noiseType = 'uniform'

simuParas['nTrain'] = nTrain
simuParas['batchsize'] = batchsize
simuParas['nValid'] = nValid
simuParas['nTest'] = nTest
simuParas['L'] = L
simuParas['noiseLevel'] = noiseLevel
simuParas['noiseType'] = noiseType
simuParas['filterType'] = filterType
simuParas['signalMode'] = signalMode
simuParas['trainMode'] = trainMode
simuParas['filterMode'] = filterMode
simuParas['selectMode'] = selectMode
simuParas['graphType'] = graphType
simuParas['alpha'] = alpha
simuParas['nEpochs'] = nEpochs
simuParas['device'] = device
simuParas['early_stop_criteria'] = early_stop_criteria
# simuParas['useZtoTrain'] = False

tMax = None # Maximum number of diffusion times (W^t for t < tMax)
tMax = 5
simuParas['tMax'] = tMax

## model parameters
modelParas = {}
modelParas['filterTrainType'] = filterTrainType
modelParas['C'] = C
modelParas['q'] = q
modelParas['K'] = K

## Experiment parameters
expParas = {}
expParas['nRealiz'] = 2



Experiment: ER graph



In [ ]:
## q = 1
graphType = 'ER' # Type of graph
graphOptions = {} # Dictionary of options to pass to the graphTools.createGraph function
graphOptions['probIntra'] = 0.3 # Probability of drawing edges

simuParas['graphType'] = graphType
simuParas['nNodes'] = 20
expParas['nRealiz'] = 5
simuParas['nEpochs'] = 30
modelParas['q'] = 2
P = 400
batchsize_slog = P
nValid = P
nTest = P
simuParas['batchsize'] = batchsize
simuParas['nValid'] = nValid
simuParas['nTest'] = nTest
simuParas['nTrain'] = 20000
simuParas['alpha'] = 1.0
simuParas['batchsize'] = P
simuParas['nValid'] = P
simuParas['nTest'] = P
simuParas['L'] = 3
result_1 = SLOGexperiment.slog_experiments(simuParas = simuParas,
                 graphOptions = graphOptions,
                 modelParas = modelParas, expParas = expParas)



Device selected: cpu
<class 'numpy.float64'>
(g_batch_generate) Generating h filter
[0.70608318 0.75283842 0.77285359 1.45746169 1.3998154  1.3264373
 0.7976613  0.81151985 1.21582092 1.14174441 1.1581624  0.83567121
 0.84658378 1.0650062  1.03739105 0.99730661 0.98467083 0.87928556
 0.90155117 0.91213513]
[20000, 20000]
Number of Batches: 50

Epoch 1

    (E:  1, B:   1) 
	 Loss: 0.5009 [T] 0.1082 [V] 	 RE: 1.8424 [T] 	 RE: 0.8619 [V] 	 Best Loss: 0.1082 [V] 	 Loss: 0.1525 [Test]

    (E:  1, B:  41) 
	 Loss: 0.1525 [T] 0.0927 [V] 	 RE: 1.0099 [T] 	 RE: 0.7976 [V] 	 Best Loss: 0.0927 [V] 	 Loss: 0.1608 [Test]
Mean training time =  0.08304796616000658

Epoch 2

    (E:  2, B:  31) 
	 Loss: 0.1477 [T] 0.1368 [V] 	 RE: 0.9859 [T] 	 RE: 0.9688 [V] 	 Best Loss: 0.0927 [V] 	 Loss: 0.1528 [Test]
Mean training time =  0.06185402796000744

Epoch 3

    (E:  3, B:  21) 
	 Loss: 0.1415 [T] 0.1365 [V] 	 RE: 0.9609 [T] 	 RE: 0.9677 [V] 	 Best Loss: 0.0927 [V] 	 Loss: 0.1626 [Test]
Mean training ti

In [ ]:
experiment_results = result_1.experiment_results
for exp_result in experiment_results:
  myModel = exp_result['model']
  print(exp_result['model'].saveDir)
  # print(exp_result['model'])
  print(exp_result['Graph'])
  # print(exp_result['training result'])


experiments/sourceLocSLOGNET-ER-20240815020645
experiments/sourceLocSLOGNET-ER-20240815020738
experiments/sourceLocSLOGNET-ER-20240815020820
experiments/sourceLocSLOGNET-ER-20240815020904
experiments/sourceLocSLOGNET-ER-20240815020947


In [ ]:
save_test_result = True
N_realiz = expParas['nRealiz']
simuParas['N_realiz'] =  N_realiz
n0 = 0
d_noiseLvs = 0.05
N_noiseLvs = 2
N_model = len(experiment_results)
noiseLvs = n0 + d_noiseLvs*np.arange(N_noiseLvs)
result_exp_rex = np.zeros([N_noiseLvs, N_model,N_realiz])
result_exp_acc = np.zeros([N_noiseLvs, N_model,N_realiz])
result_exp_reg = np.zeros([N_noiseLvs, N_model,N_realiz])
result_elapse = np.zeros([N_noiseLvs, N_model,N_realiz])
n_model = 0
for exp_result in experiment_results:
    for n_nlvs in range(N_noiseLvs):
        simuParas['noiseLevel'] = noiseLvs[n_nlvs]
        print('Model ', n_model, ', in ', exp_result['model'].saveDir,',noiseLevel = ', noiseLvs[n_nlvs])
        result = SLOGexperiment.test_local(nNodes,P,S, exp_result, simuParas = simuParas,modelParas = modelParas)
        result_exp_rex[n_nlvs,n_model,:] = result['re_x']
        result_exp_acc[n_nlvs,n_model,:] = result['acc_x']
        result_exp_reg[n_nlvs,n_model,:] = result['re_g']
        result_elapse[n_nlvs,n_model,:] = result['elapse']
    n_model += 1
test_result = {}
test_result['result_exp_rex'] = result_exp_rex
test_result['result_exp_acc'] = result_exp_acc
test_result['result_exp_reg'] = result_exp_reg
test_result['result_elapse'] = result_elapse
test_info = {}
test_info['nTrain'] = nTrain
test_info['graphType'] = graphType
test_result['test_info'] = test_info

Model  0 , in  experiments/sourceLocSLOGNET-ER-20240815020645 ,noiseLevel =  0.0
Model  0 , in  experiments/sourceLocSLOGNET-ER-20240815020645 ,noiseLevel =  0.05
Model  1 , in  experiments/sourceLocSLOGNET-ER-20240815020738 ,noiseLevel =  0.0
Model  1 , in  experiments/sourceLocSLOGNET-ER-20240815020738 ,noiseLevel =  0.05
Model  2 , in  experiments/sourceLocSLOGNET-ER-20240815020820 ,noiseLevel =  0.0
Model  2 , in  experiments/sourceLocSLOGNET-ER-20240815020820 ,noiseLevel =  0.05
Model  3 , in  experiments/sourceLocSLOGNET-ER-20240815020904 ,noiseLevel =  0.0
Model  3 , in  experiments/sourceLocSLOGNET-ER-20240815020904 ,noiseLevel =  0.05
Model  4 , in  experiments/sourceLocSLOGNET-ER-20240815020947 ,noiseLevel =  0.0
Model  4 , in  experiments/sourceLocSLOGNET-ER-20240815020947 ,noiseLevel =  0.05


In [ ]:
print(result_exp_rex[0,:,:])
print(result_exp_reg[0,:,:])

[[ 4.70135622 20.34111184  8.04107245  5.14156441  2.46066846]
 [ 0.4427245   0.05084135  0.04260482  0.1442692   0.68713192]
 [ 1.01263753 27.20076124  6.39959031  2.02510276  4.95988972]
 [ 0.41180333  0.36126583  0.38217962  1.11282673  0.35789333]
 [ 0.3758363   0.89718753  1.03228218  0.7830238   0.35444583]]
[[ 3.50548102 16.73180864  5.70452259  4.59255163  2.30346454]
 [ 0.87949639  0.05238192  0.039478    0.28819858  0.96626847]
 [ 0.53756414 25.89913763  6.68648014  2.20601831  3.44726684]
 [ 0.20134711  0.33269689  0.45462104  0.99594964  0.31172496]
 [ 0.35580794  2.16687783  0.96635373  0.59677194  0.28011076]]
